version: "3"

services:
  worker:
    build: ./worker
    container_name: seken_worker
    volumes:
      - ./worker:/work
      - ./archives:/archives
    environment:
      TZ: "Asia/Tokyo"
      DIRNAME_ARCHIVES: /archives

  app:
    build: ./app
    container_name: seken_app
    ports:
      - "127.0.0.1:3031:3031"
    environment:
      TZ: "Asia/Tokyo"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${DB_USER:-postgres}
      DATABASE_PASSWORD: ${DB_PW:-mysecretpassword1234}
    links:
      - db
    volumes:
      - ./app:/var/www/
    stdin_open: true

  vue:
    build: vue
    volumes:
      - ./vue:/www
    ports:
      - "127.0.0.1:8901:8080"    
    tty: true

  nginx:
    build: ./nginx
    container_name: seken_nginx
    volumes:
      - ${NGINX_CONF-./nginx/development.conf}:/etc/nginx/conf.d/default.conf
      - ./vue/dist:/www
      - ./app/seken/static:/static
    links:
      - app
    ports:
      - "${NGINX_PORT:-8888}:80"
    environment:
      TZ: "Asia/Tokyo"
  
  db:
    image: postgres:10.1
    container_name: seken_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PW:-mysecretpassword1234}