# Generated by Django 3.0.7 on 2020-06-15 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='Newspaper',
            new_name='newspaper',
        ),
        migrations.AddField(
            model_name='word',
            name='_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
