# Generated by Django 3.0.7 on 2020-06-15 08:26

from django.db import migrations, models

def insertData(apps, schema_editor):
    for name, url in [
            ('mainichi', 'https://mainichi.jp/'),
            ('yomiuri', 'https://www.yomiuri.co.jp/'),
            ('nikkei', 'https://www.nikkei.com/'),
            ('asahi', 'https://www.asahi.com/'),
            ('sankei', 'https://www.sankei.com/'),
            ('hokkaido', 'https://www.hokkaido-np.co.jp/'),
            ('kahoku', 'https://www.kahoku.co.jp/'),
            ('chunichi', 'https://www.chunichi.co.jp/'),
            ('tokyo', 'https://www.tokyo-np.co.jp/'),
            ('chugoku', 'https://www.chugoku-np.co.jp/'),
            ('nishinippon', 'https://www.nishinippon.co.jp/'),
            ('ryukyushimpo', 'https://ryukyushimpo.jp/'),
            ('okinawatimes', 'https://www.okinawatimes.co.jp/'),
        ]:
        Newspaper = apps.get_model('api', 'Newspaper')
        Newspaper(name=name, url=url).save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200615_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='url',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(insertData),
    ]
